-- 테이블 생성
CREATE TABLE GENERATED_RECIPE (
  ID         NUMBER(19) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  FOOD       VARCHAR2(255 CHAR)   NOT NULL,
  INGREDIENT VARCHAR2(255 CHAR)   NOT NULL,
  RECIPE     VARCHAR2(4000 CHAR)  NOT NULL
);

-- 확인
SELECT COUNT(*) AS CNT FROM GENERATED_RECIPE;
-- DROP TABLE GENERATED_RECIPE;